repos:
  # Pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']  # allow max 10MB (default 500KB)
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements

  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix]
        exclude: '.*/migrations/.*'
      # Run the formatter
      - id: ruff-format
        exclude: '.*/migrations/.*'

  # Pyright
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: bash -c 'cd backend && poetry run pyright'
        language: system
        types: [python]
        files: ^backend/
        pass_filenames: false

  # Frontend - Prettier
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: bash -c 'cd frontend && npm run format && npm run format:check'
        language: system
        types_or: [html, css, javascript]
        files: ^frontend/
        pass_filenames: false

  # Frontend - ESLint
  # - repo: local
  #   hooks:
  #     - id: eslint
  #       name: eslint
  #       entry: bash -c 'cd frontend && npm run lint'
  #       language: system
  #       types: [javascript]
  #       files: ^frontend/.*\.js$
  #       pass_filenames: false
